
spring:
  application:
    admin:
      name: Playground
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:pg
    username: sa
    password:
    driverClassName: org.h2.Driver

  #jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    defer-datasource-initialization: true
    open-in-view: true
