spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/testjpa
    username: root
    password: test
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: false
    defer-datasource-initialization: true  # DDL 실행 후 data.sql 실행

logging:
  level:
    org.springframework.transaction: DEBUG